version: 2

sources:
  - name: data_test
    database: test  
    schema: public  
    tables:
      - name: file1_table

models:
  - name: dim_job_title
    columns:
      - name: id
        description: "Primary key for the job title dimension"
        tests:
          - unique
        type: int
      - name: job_title
        description: "Job title"
        type: varchar(255)
    tags: ["dimension"]
    materialized: table

